spring:
  application:
    name: eureka-client-user-service
server:
  port: 9601
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9600/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
