spring:
  application:
    name: hello-consumer
server:
  port: 9602
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9600/eureka/

# 配置feign远程调用接口的日志输出
logging:
  level:
    com.my.helloconsumer.feign.HelloRemoteClient: DEBUG
