spring:
  application:
    name: eureka-server
server:
  port: 9600
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9600/eureka/
